version: '2'
services:
  node:
      build: 
          context: .
          dockerfile: Dockerfile-node
      ports:
          - "443:443"
          - "8883:8883"
      volumes:
          - /root/keys:/home/root/keys/
      env_file:
          - ./secrets.env
      depends_on:
        - cassandra
  mqtt:
      build:
        context: .
        dockerfile: Dockerfile-mqtt
      ports:
           - "1883:1883"
  cassandra:
      image: cassandra
#  aedes:
#      build: 
#          context: .
#          dockerfile: Dockerfile-aedes
#      ports:
#          - "8888:8888"
#          - "8443:8443"
#      volumes:
#          - /root/keys:/home/root/keys/
#      env_file:
#          - ./secrets.env
